### ISSUE TITLE
Java 9 compatibility

### ISSUE THREAD

**Issue by gaul** [gaul/modernizer-maven-plugin#60]
modernizer fails with Java 9:

```
[ERROR] Failed to execute goal org.gaul:modernizer-maven-plugin:1.5.0:modernizer (modernizer) on project jclouds-core: Execution modernizer of goal org.gaul:modernizer-maven-plugin:1.5.0:modernizer failed.: IllegalArgumentException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.gaul:modernizer-maven-plugin:1.5.0:modernizer (modernizer) on project jclouds-core: Execution modernizer of goal org.gaul:modernizer-maven-plugin:1.5.0:modernizer failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution modernizer of goal org.gaul:modernizer-maven-plugin:1.5.0:modernizer failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.gaul.modernizer_maven_plugin.Modernizer.check(Modernizer.java:80)
        at org.gaul.modernizer_maven_plugin.ModernizerMojo.recurseFiles(ModernizerMojo.java:290)
        at org.gaul.modernizer_maven_plugin.ModernizerMojo.recurseFiles(ModernizerMojo.java:283)
        at org.gaul.modernizer_maven_plugin.ModernizerMojo.recurseFiles(ModernizerMojo.java:283)
        at org.gaul.modernizer_maven_plugin.ModernizerMojo.recurseFiles(ModernizerMojo.java:283)
        at org.gaul.modernizer_maven_plugin.ModernizerMojo.recurseFiles(ModernizerMojo.java:283)
        at org.gaul.modernizer_maven_plugin.ModernizerMojo.execute(ModernizerMojo.java:199)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
```

Upgrading the asm dependencies to 6.0_BETA addresses this issue.

**Comment by gaul** [comment]
Deployed 1.6.0-SNAPSHOT with fix.
